<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>David Kazumi - Portfólio</title>
    <link rel="stylesheet" href="styles.css">
    <style>
        /* Reset de margens e padding */
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        /* Estilo para o body com o fundo de vídeo */
        body {
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: black;
            overflow: hidden;
            font-family: 'Arial', sans-serif;
        }

        /* Estilo para o vídeo de fundo */
        video {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            object-fit: cover;
            z-index: -1;
        }

        /* Estilo para o container de conteúdo */
        .content {
            text-align: center;
            color: white;
            z-index: 1;
            padding: 20px;
        }

        /* Estilo para o título */
        h1 {
            font-size: 4em;
            font-weight: bold;
            letter-spacing: 1px;
            margin-bottom: 10px;
        }

        /* Estilo para o subtítulo */
        p {
            font-size: 1.2em;
            line-height: 1.6;
            margin-bottom: 30px;
        }

        /* Estilo para os links */
        a {
            color: #ff6f61;
            text-decoration: none;
            font-size: 1.2em;
            border: 2px solid #ff6f61;
            padding: 10px 20px;
            border-radius: 5px;
            transition: background-color 0.3s ease, color 0.3s ease;
        }

        a:hover {
            background-color: #ff6f61;
            color: white;
        }
    </style>
</head>
<body>
    <video autoplay loop muted>
        <source src="https://www.w3schools.com/html/movie.mp4" type="video/mp4">
        Your browser does not support the video tag.
    </video>

    <div class="content">
        <h1>Olá, sou David Kazumi</h1>
        <p>Sou desenvolvedor web e designer. Aqui você pode explorar meus projetos e minha jornada no mundo da tecnologia.</p>
        <a href="#contato">Entre em contato</a>
    </div>
</body>
</html>
